[package]
name = "hwp"
version = "0.1.0"
authors = ["Marco Vanotti <mvanotti@dc.uba.ar>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.21.0"
num_cpus = "1.13.0"
